FROM golang:1.12.5-stretch

RUN set -x \
  && apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates wget git bash mercurial

RUN export GO111MODULE=on                         \
  && go get -u golang.org/x/tools/cmd/goimports   \
  && go get -u github.com/onsi/ginkgo/ginkgo      \
  && export GO111MODULE=auto                      \
  && rm -rf go.mod go.sum

COPY reimport.py /usr/local/bin/reimport.py
